name: Sync to Hugging Face hub
on: 
  push:
    branches: [main]

  workflow_dispatch:  
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Force Push to Hugging Face Space
        run: |
          git config --global user.email "vardhan.aakash1@gmail.com"
          git config --global user.name "aakashv100"
          git remote add huggingface https://huggingface.co/spaces/aakashv100/gradcam_demo
          git push --force huggingface main:main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
